
name: Update Dependencies and Test on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    # go-wechaty updated
    types: [ updatedeps ]

jobs:
  UpdateDep:
    name: Update Dependency
    if: false == contains(github.head_ref, 'update-dependencies')
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.0
      with:
        go-version: 1.14.4 # optional
    - name: Update Dependency
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: go get -u ./...

    - name: Test
      run: |
        echo ${{ github.head_ref }}
        echo ${{ false == contains(github.head_ref, 'master') }}
        make install
        make test
      env:
        GIT_TRACE: 1
        GIT_CURL_VERBOSE: 1
        REF: ${{ github.head_ref }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update dependencies
        title: Update dependencies
        body: |
          - Dependency updates

          Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        branch: update-dependencies

  Build:
    name: Build on Windows
    # needs: UpdateDep
    # Test on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.0
      with:
        go-version: 1.14.4 # optional

    - name: Build Dingdongbot
      run: |
        go vet ./...
        make install
        make test
